ALTER TABLE NOTIFICATION.T_NOTIFICATION_REQUEST
    DROP CONSTRAINT IF EXISTS ck_notification_request_status;

ALTER TABLE NOTIFICATION.T_NOTIFICATION_DELIVERY
    DROP CONSTRAINT IF EXISTS ck_notification_delivery_status;

UPDATE NOTIFICATION.T_NOTIFICATION_REQUEST
SET STATUS = CASE STATUS
    WHEN 'RECEIVED' THEN 'STORED'
    WHEN 'FAILED' THEN 'DLQ'
    ELSE STATUS
END
WHERE STATUS IN ('RECEIVED', 'FAILED');

UPDATE NOTIFICATION.T_NOTIFICATION_DELIVERY
SET STATUS = CASE STATUS
    WHEN 'FAILED' THEN 'DLQ'
    ELSE STATUS
END
WHERE STATUS = 'FAILED';

ALTER TABLE NOTIFICATION.T_NOTIFICATION_REQUEST
    ALTER COLUMN STATUS SET DEFAULT 'STORED';

ALTER TABLE NOTIFICATION.T_NOTIFICATION_DELIVERY
    ALTER COLUMN STATUS SET DEFAULT 'PENDING';

ALTER TABLE NOTIFICATION.T_NOTIFICATION_REQUEST
    ADD CONSTRAINT ck_notification_request_status
        CHECK (STATUS IN (
            'STORED',
            'PROCESSING',
            'COMPLETED',
            'DLQ'
        ));

ALTER TABLE NOTIFICATION.T_NOTIFICATION_DELIVERY
    ADD CONSTRAINT ck_notification_delivery_status
        CHECK (STATUS IN (
            'PENDING',
            'SENT',
            'SENDING',
            'RETRYING',
            'DLQ'
        ));
